/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_diffcounts_free: (a: number, b: number) => void;
export const __wbg_difftreebuilder_free: (a: number, b: number) => void;
export const __wbg_get_diffcounts_added: (a: number) => number;
export const __wbg_get_diffcounts_removed: (a: number) => number;
export const __wbg_set_diffcounts_added: (a: number, b: number) => void;
export const __wbg_set_diffcounts_removed: (a: number, b: number) => void;
export const build_diff_tree: (a: any, b: any, c: number) => [number, number, number];
export const build_diff_tree_for_package: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => any;
export const count_diff: (a: number, b: number, c: number, d: number) => number;
export const difftreebuilder_build_tree: (a: number) => [number, number, number];
export const difftreebuilder_new: (a: number) => number;
export const difftreebuilder_set_from_files: (a: number, b: any) => [number, number];
export const difftreebuilder_set_to_files: (a: number, b: any) => [number, number];
export const fetch_and_extract_package: (a: number, b: number, c: number, d: number, e: number, f: number) => any;
export const get_diff_content: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number];
export const get_diff_for_path: (a: number, b: number, c: number, d: number) => [number, number, number];
export const prefetch_package: (a: number, b: number, c: number, d: number, e: number, f: number) => any;
export const wasm_bindgen__closure__destroy__hf610b7ce91a92bfa: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h26d2e9b1279394f7: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hd42d7be819e8e283: (a: number, b: number, c: any) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
